### ISSUE TITLE
Fix typos in function names

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/system-image-node-module#2] opened 2018-03-06 20:24 UTC
There are some typos that need to be fixed in the module and in downstream projects like the UBports Installer.

- [x] upstream
- [x] downstream

**Comment by gsilvapt** [comment] 2018-03-24 00:02
In this project, I was only able to find `getLatestVesion`. I'm sending a PR over with this information. Can we list other downstream projects you can think of that it is worth looking for typos in this issue to keep things in one place?

**Comment by NeoTheThird** [comment] 2018-03-27 08:23
That's correct, good job. I intentionally left the description a little vague, since it's an easy fix and a good opportunity for newcomers to get acquainted with the code. The only official downstream-project is the UBports Installer (eg. https://github.com/ubports/ubports-installer/blob/master/src/system-image.js#L75), if you could send a PR there, that would be appreciated. Of course we will have to release a new version of this module before merging it there, though.

**Comment by gsilvapt** [comment] 2018-03-27 08:56
Awesome!, thanks for reviewing @NeoTheThird . I was already looking to typos in the Ubuntu Installer. I was not sure where the project had dependencies on aside from the installer itself. I did started taking a look at it but then had an important issue to debate with Marius. I guess I'm moving this conversation to the PR I opened yesterday as the issue is now then on the downstream project.

Thanks!

**Closed as completed** 2018-05-01 15:01 UTC
Labels: bug, help wanted, good first issue
